# Generated by Django 4.1.7 on 2023-04-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_product_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=models.ImageField(blank=True, default=(), null=True, upload_to='Prod_pic/'),
        ),
    ]
