# Generated by Django 4.1.7 on 2023-04-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
